#!/bin/zsh

function tmux_send_key_to_pane_0 {
  buffer_content=$BUFFER
  BUFFER="tmux send-key -t 0 "
  BUFFER+="$buffer_content enter"
  zle accept-line
}
zle -N tmux_send_key_to_pane_0
bindkey '^s' tmux_send_key_to_pane_0
